baseURL = "https://bicepforreal.com"
languageCode = "en-us"
title = "Bicep for Real"
theme = "kube"
description = "Kube is a professional  and a responsive Hugo theme for developers and designers that offers a documentation section mixed with a landing page and a blog"
Paginate = 4
googleAnalytics: G-JMZ25S5EFM
[Params]
  RSSLink = "/index.xml"
  author = "Sam Cogan" # add your company name
  github = "sam-cogan" # add your github profile name
  twitter = "samcogan" # add your twitter profile
  email = "mail@samcogan.com"

[[menu.main]]
    name = "Episodes"
    weight = 10
    url = "/docs/"
[[menu.main]]
    name = "Getting Started"
    weight = 5
    url = "/blog/getting-started/"
[[menu.main]]
    name = "Blog"
    weight = 30
    url = "https://samcogan.com"
[[menu.main]]
    name = "Donate"
    weight = 50
    url = "/blog/donate/"
[[menu.main]]
    name = "Github"
    weight = 40
    url = "https://github.com/sam-cogan/lambda-toys-api-infrastructure"


