baseURL = "https://bicepforreal.com"
languageCode = "en-us"
title = "Bicep for Real"
theme = "kube"
description = "Kube is a professional  and a responsive Hugo theme for developers and designers that offers a documentation section mixed with a landing page and a blog"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Sam Cogan" # add your company name
  github = "sam-cogan" # add your github profile name
  twitter = "samcogan" # add your twitter profile
  email = "mail@samcogan.com"

[[menu.main]]
    name = "Episodes"
    weight = 10
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = 20
    url = "https://samcogan.com"
[[menu.main]]
    name = "Faq"
    weight = 30
    url = "/faq/"
